POST http://127.0.0.1:3000/user/register HTTP/1.1
content-type: application/json

{
    "login": "louis",
    "password": "hi"
}

###

DELETE http://127.0.0.1:3000/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvdWlzIiwiZXhwIjoxNjc5NjczMzU1LCJpYXQiOjE2Nzk1ODY5NTV9.YDSSW5ioquxlA_PVLMQJQEBB2COMaJTfD-5aGhtK6go

###

PUT http://127.0.0.1:3000/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvdWlzIiwiZXhwIjoxNjc5NjczMzU1LCJpYXQiOjE2Nzk1ODY5NTV9.YDSSW5ioquxlA_PVLMQJQEBB2COMaJTfD-5aGhtK6go
Content-Type: application/json

{
    "password": "hia"
}