POST http://127.0.0.1:3000/user/register HTTP/1.1
content-type: application/json

{
    "login": "lolo",
    "password": "hi"
}

###

DELETE http://127.0.0.1:3000/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvbG8iLCJleHAiOjE2Nzk3NDI3MzcsImlhdCI6MTY3OTY1NjMzN30.El4-MW3_YJw_GwMdAJRVHDjQK2ULzTYiZ24NqxwA8Hk
###

PUT http://127.0.0.1:3000/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvbG8iLCJleHAiOjE2Nzk3NDI3MDksImlhdCI6MTY3OTY1NjMwOX0.2rzOV5ykSh4eQD-ApauMNBsakZN40o36wzgso2Za84o
Content-Type: application/json

{
    "password": "hia"
}