POST http://127.0.0.1:3000/user/auth HTTP/1.1
content-type: application/json

{
    "login": "lolo",
    "password": "hi"
}

###

GET http://127.0.0.1:3000/product HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvbG8iLCJleHAiOjE2ODAxMzMzNTAsImlhdCI6MTY4MDA0Njk1MH0.T-qM6v87u2QcpPJYPYcDVS75WQlKDlxY0RXw4RxOH3A