POST http://127.0.0.1:3000/user/auth HTTP/1.1
content-type: application/json

{
    "login": "kyo",
    "password": "hi"
}

###

GET http://127.0.0.1:3000/restricted HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImxvdWlzIiwiZXhwIjoxNjc5NjczMzU1LCJpYXQiOjE2Nzk1ODY5NTV9.YDSSW5ioquxlA_PVLMQJQEBB2COMaJTfD-5aGhtK6go